### ISSUE TITLE
error when using cool as input

### ISSUE THREAD

**Issue by biozzq** [ay-lab/selfish#18]
Dear @ay-lab 

I updated to the latest version, it gives me an error when using following command, 

command,
`selfish -f1 WT_KR_corrected_matrix.cool -f2 8WM_KR_corrected_matrix.cool -nb -o WT_8WM -d 2000000 -t 1 -ch chr1 -r 50kb`

error
```
Reading Contact Map 1
This does not appear to be a HiC file magic string is incorrect
Traceback (most recent call last):
  File "elfish", line 8, in <module>
    sys.exit(main())
  File "/lib/python3.8/site-packages/selfish/selfish.py", line 814, in main
    o, x, y, q_val, changes_array = DCI(f1,
  File "/lib/python3.8/site-packages/selfish/selfish.py", line 388, in DCI
    a = readHiCFile(f1, chromosome, chromosome2,
  File "/lib/python3.8/site-packages/selfish/selfish.py", line 651, in readHiCFile
    result = straw.straw('KR', f, str(chr), str(chr2), 'BP', res)
  File "/lib/python3.8/site-packages/straw/straw.py", line 470, in straw
    master=list1[0]
TypeError: 'int' object is not subscriptable
```

Sincerely,
Zheng zhuqing

**Comment by biozzq** [comment]
Dear @ay-lab 

I found the cool file must be in the working directory. Is this right? The above error occurred maybe because I added the absolute path to the cool files, e.g., `selfish -f1 /home/WT/WT_KR_corrected_matrix.cool`. Hope you can help me to confirm this.

Best,

**Comment by ay-lab** [comment]
Hi, I updated the code and it shouldn't give you any error now. So, now instead of using "-nb" please use "-norm" and provide your normalization name (when you create the cool files your normalized values are stored in a column with a specific name). Let me know if you have any problem.

**Comment by biozzq** [comment]
Dear @ay-lab 

Thank you. I think the  option `-norm` should be set to `-norm weight` when the input is cool/mcool file. Is this right?

Sincerely,
Zheng zhuqing

**Comment by ay-lab** [comment]
You don't need to specify the normalization method if the biases are stored in the "weight" column (default). Use it when your biases are stored in a different column (e.g., -norm KR).

**Comment by biozzq** [comment]
Do you mean that I need run without setting `-norm`, as following?
`selfish -f1 ${dir}/WT_KR_corrected_matrix.cool -f2 ${dir}/10MM_KR_corrected_matrix.cool -o WT_10MM_${chr}.txt -d 2000000 -t 1 -ch ${chr} -ch2 ${chr} -r 50kb`

Best,

**Comment by biozzq** [comment]
Dear @ay-lab 

Also, the results are substantial changes when updating from 1.13 to 1.14.

The results from version 1.13, `selfish -f1 WT_KR_corrected_matrix.cool -f2 10MF_KR_corrected_matrix.cool -nb -o WT_10MF_${chr}.txt -d 2000000 -t 1 -ch ${chr} -ch2 ${chr} -r 50kb`
```
chr18	3050000	3100000	chr18	3300000	3350000	0.9983806007164722	-0.6327144677687468
chr18	3050000	3100000	chr18	3350000	3400000	0.9983806007164722	0.15530246124622987
chr18	3050000	3100000	chr18	3400000	3450000	0.9983806007164722	0.6577010781328566
chr18	3050000	3100000	chr18	3450000	3500000	0.9983806007164722	0.08816708551268787
chr18	3050000	3100000	chr18	3500000	3550000	0.9983806007164722	0.16133626472833118
chr18	3050000	3100000	chr18	3550000	3600000	0.9983806007164722	0.026869754130006522
chr18	3050000	3100000	chr18	3900000	3950000	0.20195219642852477	-0.5789627530453949
chr18	3050000	3100000	chr18	3950000	4000000	0.0017211223646492629	-0.8290971178338075
chr18	3100000	3150000	chr18	3250000	3300000	0.9983806007164722	-0.5823840124086228
chr18	3100000	3150000	chr18	3300000	3350000	0.9983806007164722	-1.0849147635453271

```
The results from version 1.14, `selfish -f1 WT_KR_corrected_matrix.cool -f2 10MF_KR_corrected_matrix.cool -o WT_10MF_${chr}.txt -d 2000000 -t 1 -ch ${chr} -ch2 ${chr} -r 50kb`
```
chr18	3050000	3100000	chr18	3300000	3350000	0.054194336994536164	-0.2277179399677472
chr18	3050000	3100000	chr18	3350000	3400000	0.02865730872159884	-0.010425227313333734
chr18	3050000	3100000	chr18	3400000	3450000	0.312867690114457	0.0013108026779620338
chr18	3050000	3100000	chr18	3500000	3550000	0.9658494459125764	-0.0017761510735220215
chr18	3050000	3100000	chr18	3550000	3600000	0.529212454018269	-0.0015482062092573403
chr18	3050000	3100000	chr18	3900000	3950000	0.06567451794803292	-0.0002517360353078533
chr18	3050000	3100000	chr18	3950000	4000000	1.9280753897058133e-06	-0.003559347924635852
chr18	3100000	3150000	chr18	3250000	3300000	0.2610043589304204	-0.004660099496798458
chr18	3100000	3150000	chr18	3300000	3350000	0.04315927283428969	-0.003163609356025403
```

**Comment by ay-lab** [comment]
Right, you don't need to specify the -norm parameter (if it doesn't give you an error you are fine). I think in 1.13 selfish was reading the raw data for your dataset (by using the -nb parameter) rather than the normalized data. The new version should give you better results. Let me know how the new results look like to you.

**Comment by biozzq** [comment]
Dear @ay-lab 

After running following command `selfish -f1 WT_KR_corrected_matrix.cool -f2 10MF_KR_corrected_matrix.cool -o WT_10MF_${chr}.txt -d 2000000 -t 1 -ch ${chr} -ch2 ${chr} -r 50kb`, no significant differential chromatin interactions were identified (defined by q-value < 0.01 and abs(log_FC)>1 ) in the genome-wide (the genome wide lowest log_FC is -0.9294568005517112 and the largest one is 0.4660991685629558). Thus, I want to confirm with you whether the q-value and Log_FC have a correct distribution. Please note that I only used the results from the shortest chromosome to generate the following plot.
![image](https://user-images.githubusercontent.com/15704257/119336579-68a02300-bcc0-11eb-92e6-d7caa35eee40.png)

Sincerely,
Zheng zhuqing

**Comment by ay-lab** [comment]
I know for human and mouse data we usually get bigger fold changes than what you got here. Can you please run this command "cooler dump -b  -t pixels --header --join -r 3:10M-12M your_file.cooler | head" and see what it returns?

**Comment by biozzq** [comment]
Dear @ay-lab 

Yes, the results returned are as follows when using above command. 
`cooler dump -b -t pixels --header --join -r chr3:10M-12M WT_KR_corrected_matrix.cool | head`
```
chrom1	start1	end1	chrom2	start2	end2	count	balanced
chr3	10000000	10050000	chr3	10000000	10050000	503	0.13662
chr3	10000000	10050000	chr3	10050000	10100000	193	0.0521065
chr3	10000000	10050000	chr3	10100000	10150000	102	0.028903
chr3	10000000	10050000	chr3	10150000	10200000	77	0.0230077
chr3	10000000	10050000	chr3	10200000	10250000	138	0.0360434
chr3	10000000	10050000	chr3	10250000	10300000	132	0.0342301
chr3	10000000	10050000	chr3	10300000	10350000	117	0.0257264
chr3	10000000	10050000	chr3	10350000	10400000	48	0.0117067
chr3	10000000	10050000	chr3	10400000	10450000	30	0.00838386
```
To better examine this issue, I also present the process of generating the cool files here,
1 generating valid pairs using HiC-Pro,
2 convert the valid pairs to cool format using the HiC-Pro `build_matrix` and the hicexplorer `hicConvertFormat`,
3 normalization, all samples / replicates are normalized to the same read coverage using the hicexplorer `hicNormalize`,
4 correct (KR, --perchr) the data with the hicexplorer `hicCorrectMatrix`

Sincerely,
Zheng zhuqing

**Comment by ay-lab** [comment]
Sorry, I am not that familiar with creating cooler files but these should help: 
1- https://hub.gke2.mybinder.org/user/open2c-cooler-binder-54mqal9p/notebooks/cooler_cli.ipynb#Text-export
2- https://hms-dbmi.github.io/hic-data-analysis-bootcamp/#1

**Comment by biozzq** [comment]
Dear @ay-lab 

Thank you. I think both pipelines used to generate the cool file are ok. Can you see any abnormal in my cool file, as I got such smaller fold changes here? Thank you for your time.

Sincerely,
Zheng zhuqing

**Comment by ay-lab** [comment]
No your cool data looks OK (I am not sure about the normal fold-change range for your data though). One thing I can suggest is that you ignore the fold changes (for now) and see if the reported differential interactions (based on only the q-val) can find some of the obvious differences you can visually see in the contact maps.

**Comment by biozzq** [comment]
Dear @ay-lab 

Sorry, during analysis the results generated by selfish, several questions occurred to me.

 First, how to interpret p-values of 0? I found many contacts with a p-value of 0. 
```
CHR1    LOC1_start      LOC1_end        CHR2    LOC2_start      LOC2_end        Q_VAL   LOG_FOLD_CHANGE
chr10   100800000       100850000       chr10   102050000       102100000       0.0     0.00012238696260486148
chr10   103250000       103300000       chr10   104200000       104250000       0.0     -0.006668733100241488
```
Second, I used `fancplot -p mirror` to visual the comtact maps, here I have selected the contact maps with a p value of `2.624669909440033e-300`, however, the changes are not obvious.
```
chr13   65350000        65400000        chr13   66800000        66850000        2.624669909440033e-300  -0.0068627480719538605
```
The plot looks like following, above contact is highlighted by red circle.
![捕获](https://user-images.githubusercontent.com/15704257/120475220-a6e1c480-c3db-11eb-91fc-86a46935643f.PNG)

Sincerely.
Zheng zhuqing

**Comment by ay-lab** [comment]
Hi, is there any chance you can share one of the chromosomes so that I can test selfish on?

**Comment by biozzq** [comment]
Dear @ay-lab 

I am very glad to share the cool file I used with you. The cool file has been normalized to the same read coverage and corrected by KR algorithm by using the hicexplorer. The files has been attached here https://drive.google.com/file/d/1SgHPwertDrEVJxcuuM_W_AAC0ZACEwOp/view?usp=sharing

Thank you for your time.

Sincerely.
Zheng zhuqing

**Comment by ay-lab** [comment]
I am getting 14591 differential interactions for chromosome 10 and 10159 differentials for chromosome 13 for q<0.01. Is that what you get?

python selfish/selfish.py  -f1 WT_KR_corrected_matrix.cool -f2 10MF_KR_corrected_matrix.cool  -o out.txt -d 2000000 -t 0.01 -ch chr13 -r 50kb

**Comment by biozzq** [comment]
Dear @ay-lab 
I got the same number differential interactions using command: `selfish -f1 ${dir}/WT_KR_corrected_matrix.cool -f2 ${dir}/10MF_KR_corrected_matrix.cool -o WT_10MF_${chr}.txt -d 2000000 -t 1 -ch ${chr} -ch2 ${chr} -r 50kb`
```
grep "^chr10" results | awk '$7 < 0.01' | wc -l
14591
grep "^chr13" results | awk '$7 < 0.01' | wc -l
10159
```

**Comment by biozzq** [comment]
Dear @ay-lab 

Are you still following this issue? I'm curious about the conclusions you get after visualizing those differential interactions (based on only the q-val).

Sincerely,
Zheng zhuqing
