### ISSUE TITLE
ERROR : ModuleNotFoundError: No module named 'straw'

### ISSUE THREAD

**Issue by Z-H-Zhang** [ay-lab/selfish#22]
I used the output of hicpro as the input of selfish, and encountered the following problems. How can I solve the following problems?

Traceback (most recent call last):
  File "/home/zhzhang/miniconda3/envs/selfish/bin/selfish", line 5, in <module>
    from selfish.selfish import main
  File "/home/zhzhang/miniconda3/envs/selfish/lib/python3.8/site-packages/selfish/selfish.py", line 13, in <module>
    import straw
ModuleNotFoundError: No module named 'straw'

**Comment by RobTesf** [comment]
Hi,
Is there a solution for this?
I see that I have hic-straw installed. But importing straw does not work since the module is named hicstraw and the command should be `hicstraw.straw()`.
Do I have to install an older version of straw?
Thanks in advance

**Comment by RobTesf** [comment]
Here is my fix for those wondering
file: selfish.py
line 13
```
import hicstraw
```

line 652
```
def readHiCFile(f, chr, chr2, res, distance, norm_method):
    """
    :param f: .hic file path
    :param chr: Which chromosome to read the file for
    :param res: Resolution to extract information from
    :return: Numpy matrix of contact counts
    """
    if not norm_method:
        result = hicstraw.straw('observed','KR', f, str(chr), str(chr2), 'BP', res)
    else:
        result = hicstraw.straw('observed',str(norm_method), f, str(chr), str(chr2), 'BP', res)
    x = np.array(result[0].binX) // res
    y = np.array(result[1].binY) // res
    val = np.array(result[2].counts)
    #n = max(max(x), max(y)) + 1
    x = np.append(x,[result[i].binX // res for i in range(1,len(result))])
    y = np.append(y,[result[i].binY // res for i in range(1,len(result))])
    val = np.append(val,[result[i].counts // res for i in range(1,len(result))])
    n1 = max(x) + 1
    n2 = max(y) + 1
    o = np.zeros((n1, n2))
    o[x, y] = val
    #o[y, x] = val
    np.nan_to_num(o, copy=False, nan=0, posinf=0, neginf=0)
    return o
```

**Comment by RobTesf** [comment]
there is an error in my previous code. Do not devide the values by res...
```
val = np.append(val,[result[i].counts for i in range(1,len(result))])
```

**Comment by joloagui** [comment]
Hello, 

I uninstalled hic-straw 1.3.1 and installed hic-straw 0.0.6 and this fixed the issue. This was the version out when the tool was created. 

Joe
